services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=mysql+mysqlconnector://root:password@db:3306/moniepoint
    depends_on:
      - db
    volumes:
      - ./upload:/app/upload
      - ./uploads:/app/uploads
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: moniepoint
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./moniepoint.sql:/docker-entrypoint-initdb.d/moniepoint.sql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge