"""empty message

Revision ID: f0f0da5c1fda
Revises: c8de51445c64
Create Date: 2025-09-30 13:26:42.813073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0f0da5c1fda'
down_revision = 'c8de51445c64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('information', schema=None) as batch_op:
        batch_op.drop_column('transcript')

    # ### end Alembic commands ###
